# Generated by Django 5.1.1 on 2024-10-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.SmallIntegerField(null=True),
        ),
    ]
